<script type="text/javascript" src="<?php echo $this->bootstrapJS ?>"></script>
<link rel="stylesheet" href="<?php echo $this->bootstrapCSS ?>" />
<script type="text/javascript" src="<?php echo $this->SRCspin ?>"></script>
<script type="text/javascript" src="<?php echo $this->SRCspinmin ?>"></script>
<link rel="stylesheet" href="<?php echo $this->jqueryUICss ?>" />
<link href="<?php echo $this->dataTablesDemoCSS ?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->dataTablesJUICSS ?>" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->dataTablesJS; ?>"></script>
<script>
    $(document).ready(function() {
        $('#pluginlist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            <?php if ($this->cmdd == "listall"): ?>
                "aoColumns": [null, null],
            <?php else: ?>
                "aoColumns": [null, null, null, {"bSortable": false}],
            <?php endif; ?>
            "bStateSave": true
        });
        $('#startscan').click(function() {
            $('#greyOverlay').show();
        });
    });

</script>
<div id="greyOverlay" style="
     display:none;
     position:absolute;
     top:0px;
     left:0px;
     bottom:0px;
     right:0px;
     width:100%;
     height:100%;
     z-index: 1;
     background-color: #222;
     opacity: 0.7;">
    &nbsp;</div>


<style>
    .clearfix:after {
        content: ".";
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0;
    }

    body{background-color: #7F7F7F!important}

    #lw_fe_inputelement_lw_formular_template{width: 800px;height: 600px;}
    #tabs ul li a{color: #fff;}

    .activeline {background: #e8f2ff !important;}

    .active{background-color: #777;}

    .description {
        margin-bottom:60px;
        border:1px solid #aaa;
        border-radius: 5px;
        background-color:#eee;
        padding:10px;
    }

    legend.lwadminform {
        height: 20px;
        margin-bottom: 2px;
        line-height: 20px;
        width: 70px;
    }
    html body div#lwContent div {
        font-size: 12px!important;
    }

    fieldset.lwadminform {
        position: relative;
    }


    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center form#gotoform input#gotoid {
        width: 45px;
        margin-bottom: 0;
    }
    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center {
        height: 35px;
    }    


    #container{
        background-color: #fff;
        border: 1px solid #bbb;
        border-radius: 10px;
        padding: 10px;
    }
    

    
    #pluginlist{font-weight: bold;margin: 0;}
    #pluginlist thead th{cursor: pointer;}
    
    .table-hover tbody tr:hover td, .table-hover tbody tr:hover th {background-color: #eee;}
</style>

<fieldset class="lwadminform">
    <legend class="lwadminform">PLuginlist</legend>
    <div id="container">

        <input type="button" class="btn btn-primary" title="change view" onclick="
        self.location.href = '<?php echo $this->link; ?>';
           " value="<?php echo $this->linktext; ?>">

        <input type="button" class="btn btn-primary" id="startscan" title="start new plugin scan" onclick="
        var opts = {
            lines: 13, // The number of lines to draw
            length: 16, // The length of each line
            width: 14, // The line thickness
            radius: 25, // The radius of the inner circle
            corners: 1, // Corner roundness (0..1)
            rotate: 0, // The rotation offset
            color: '#ddd', // #rgb or #rrggbb
            speed: 1, // Rounds per second
            trail: 44, // Afterglow percentage
            shadow: true, // Whether to render a shadow
            hwaccel: false, // Whether to use hardware acceleration
            className: 'spinner', // The CSS class to assign to the spinner
            zIndex: 2e9, // The z-index (defaults to 2000000000)
            top: '350', // Top position relative to parent in px
            left: 'auto' // Left position relative to parent in px
        };
        var target = document.getElementById('lwTopnavi');
        var spinner = new Spinner(opts).spin(target);

        self.location.href = '<?php echo $this->link_scan; ?>';
           " value="<?php echo $this->linktext_scan; ?>">

        <?php if ($this->cmdd == "listall"): ?>
            <div class="clearfix" style="float:right;font-weight: bold;">Legende: Plugin <span style="color:green;">in Verwendung</span> / <span style="color:darkred;">nicht in Verwendung</span></div>
        <?php else :?>
            <div class="clearfix" style="float:right;font-weight: bold;">Legende: Aufruf eines <span style="color:green;">installierten</span> / <span style="color:darkred;">nicht installierten</span> Plugins</div>
        <?php endif; ?>
        <div style="margin-top: 10px;"><span style="font-size: 14px;">Anzeige : <span style="font-size: 16px;font-weight: bold;font-style: italic;"><?php echo $this->title; ?></span></span>
        <span style="text-align: right;font-size: 14px;font-weight: bold;float: right;">Last Scan: <?php echo $this->lastscandate; ?></span>
        </div>

        <div id="datatable_container">
            <table id="pluginlist" class="table table-bordered table-hover" width="100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <?php if ($this->cmdd == "listall"): ?>
                            <th>Modul</th>
                        <?php else: ?>
                            <th>Typ</th>
                            <th>Plugin Aufruf</th>
                            <th>&nbsp;</th>
                        <?php endif; ?>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($this->array as $entry) : ?>
                        <tr>
                                <?php
                                if ($this->cmdd == "listall") {
                                    $green = false;
                                    foreach ($this->array2 as $arrEntry) {
                                        if ($arrEntry["plugin_name"] == $entry["plugin_name"]) {
                                            $green = true;
                                        }
                                    }
                                }
                                else {
                                    foreach ($this->array2 as $arrEntry) {
                                        $pluginnameArray[] = $arrEntry["plugin_name"];
                                    } 
                                    if(!(in_array($entry["plugin_name"], $pluginnameArray))){
                                        $green = false;
                                    }
                                    else {
                                        $green = true;
                                    }
                                }
                                ?>
                            <td <?php if ($green) { echo "style=\"color: green;\""; } else { echo "style=\"color: darkred;\"";} ?> ><?php echo $entry["name"]; ?></td>

                            <?php if ($this->cmdd != "listall"): ?>
                                <td <?php if ($green) { echo "style=\"color: green;\""; } else { echo "style=\"color: darkred;\"";} ?> ><?php echo $entry["typ"]; ?></td>
                            <?php endif; ?>

                            <td <?php if ($green) { echo "style=\"color: green;\""; } else { echo "style=\"color: darkred;\"";} ?> ><?php echo $entry["plugin_aufruf"]; ?></td>

                            <?php if ($this->cmdd != "listall"): ?>
                                <td <?php if ($green) { echo "style=\"color: green;\""; } else { echo "style=\"color: darkred;\"";} ?> ><a href="
                                    <?php 
                                        if($entry["typ"] == "Template") {
                                            echo $this->baseUrl."?obj=template&cmd=edit&tid=".$entry["id"];
                                        }
                                        elseif($entry["typ"] == "CObject"){
                                            echo $this->baseUrl."?obj=cobject&cmd=edit&cobject=".$entry["id"];
                                        }elseif($entry["typ"] == "Page"){
                                            $firstLetter = substr($entry["plugin_aufruf"], 0,1);
                                            if($firstLetter == "M"){
                                                echo $this->baseUrl."?obj=content&index=".$entry["id"]."&container=c1";
                                            }else{
                                                echo $this->baseUrl."?obj=content&index=".$entry["id"]."&container=c2";
                                            }
                                        };
                                    ?>" style="background-color: transparent;padding: 5px;display: block;"><i class="icon-share-alt"></i></a></td>
                            <?php endif; ?>
                        </tr>		
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</fieldset>