<script type="text/javascript" src="<?php echo $this->bootstrapJS ?>"></script>
<link rel="stylesheet" href="<?php echo $this->bootstrapCSS ?>" />
<script type="text/javascript" src="<?php echo $this->SRCdataTables; ?>"></script>
<link href="<?php echo $this->SRCdataTablesCSS ?>" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->SRCspin ?>"></script>
<script type="text/javascript" src="<?php echo $this->SRCspinmin ?>"></script>
<script>
    $(document).ready(function() {
        $('#epluginlist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumns": [{"bSortable": false}, null, null, {"bSotable": false}],
            "bStateSave": true
        });
        $('#startscan').click(function() {
            $('#greyOverlay').show();
        });
    });

</script>
<div id="greyOverlay" style="
     display:none;
     position:absolute;
     top:0px;
     left:0px;
     bottom:0px;
     right:0px;
     width:100%;
     height:100%;
     z-index: 1;
     background-color: #222;
     opacity: 0.7;">
    &nbsp;</div>


<style>
    body{background-color: #7F7F7F!important}

    #lw_fe_inputelement_lw_formular_template{width: 800px;height: 600px;}
    #tabs ul li a{color: #fff;}

    .activeline {background: #e8f2ff !important;}

    .active{background-color: #777;}

    .description {
        margin-bottom:60px;
        border:1px solid #aaa;
        border-radius: 5px;
        background-color:#eee;
        padding:10px;
    }

    legend.lwadminform {
        height: 20px;
        margin-bottom: 2px;
        line-height: 20px;
        width: 70px;
    }
    html body div#lwContent div {
        font-size: 12px!important;
    }

    fieldset.lwadminform {
        position: relative;
    }


    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center form#gotoform input#gotoid {
        width: 45px;
        margin-bottom: 0;
    }
    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center {
        height: 35px;
    }    


    #container{
        background-color: #fff;
        border: 1px solid #bbb;
        border-radius: 10px;
        padding: 10px;
    }

</style>

<fieldset class="lwadminform">
    <legend class="lwadminform">PLuginlist</legend>
    <div id="container">

        <input type="button" class="btn btn-primary" title="change view" onclick="
        self.location.href = '<?php echo $this->link; ?>';
           " value="<?php echo $this->linktext; ?>">

        <input type="button" class="btn btn-primary" id="startscan" title="start new plugin scan" onclick="
        var opts = {
            lines: 13, // The number of lines to draw
            length: 16, // The length of each line
            width: 14, // The line thickness
            radius: 25, // The radius of the inner circle
            corners: 1, // Corner roundness (0..1)
            rotate: 0, // The rotation offset
            color: '#ddd', // #rgb or #rrggbb
            speed: 1, // Rounds per second
            trail: 44, // Afterglow percentage
            shadow: true, // Whether to render a shadow
            hwaccel: false, // Whether to use hardware acceleration
            className: 'spinner', // The CSS class to assign to the spinner
            zIndex: 2e9, // The z-index (defaults to 2000000000)
            top: '350', // Top position relative to parent in px
            left: 'auto' // Left position relative to parent in px
        };
        var target = document.getElementById('lwTopnavi');
        var spinner = new Spinner(opts).spin(target);

        self.location.href = '<?php echo $this->link_scan; ?>';
           " value="<?php echo $this->linktext_scan; ?>">

        <div style="margin-top: 10px;"><span style="font-size: 14px;">Anzeige : <span style="font-size: 16px;font-weight: bold;font-style: italic;"><?php echo $this->title; ?></span></span>
        <span style="text-align: right;font-size: 14px;font-weight: bold;float: right;">Last Scan: <?php echo $this->lastscandate; ?></span>
        </div>


        <table id="pluginlist" class="table table-bordered table-hover" width="100%">
            <thead>
                <tr>
                    <th width="5%">ID</th>
                    <th width="15%">Typ</th>
                    <th width="20%">Name</th>
                    <th width="60%">Plugin Aufruf</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->array as $entry) : ?>
                    <tr>
                            <?php
                            if ($this->cmdd == "listall") {
                                $green = false;
                                foreach ($this->array2 as $arrEntry) {
                                    if ($arrEntry["plugin_name"] == $entry["plugin_name"]) {
                                        $green = true;
                                    }
                                }
                            }
                            else {
                                foreach ($this->array2 as $arrEntry) {
                                    $pluginnameArray[] = $arrEntry["plugin_name"];
                                } 
                                if(!(in_array($entry["plugin_name"], $pluginnameArray))){
                                    $green = false;
                                }
                                else {
                                    $green = true;
                                }
                            }
                            ?>
                        <td <?php if ($green) { echo "style=\"color: green\";"; } else { echo "style=\"color: darkred\";";} ?> ><?php echo $entry["id"]; ?>&nbsp;</td>
                        <td <?php if ($green) { echo "style=\"color: green\";"; } else { echo "style=\"color: darkred\";";} ?> ><?php echo $entry["typ"]; ?></td>
                        <td <?php if ($green) { echo "style=\"color: green\";"; } else { echo "style=\"color: darkred\";";} ?> ><?php echo $entry["name"]; ?></td>
                        <td <?php if ($green) { echo "style=\"color: green\";"; } else { echo "style=\"color: darkred\";";} ?> ><?php echo $entry["plugin_aufruf"]; ?></td>
                    </tr>		
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</fieldset>